export default {
  ADD_USER: 'ADD_USER',
  USERS_LIST: 'USERS_LIST',
  ADD_MESSAGE: 'ADD_MESSAGE',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  STORE_CURRENT_USERNAME: 'STORE_CURRENT_USERNAME',
  CONNECT_TO_CHAT_SERVER: 'CONNECT_TO_CHAT_SERVER',
  DISCONNECT_FROM_CHAT: 'DISCONNECT_FROM_CHAT',
  DISCONNECTED_FROM_CHAT: 'DISCONNECTED_FROM_CHAT',
  CONNECTED_TO_CHAT: 'CONNECTED_TO_CHAT',
};
