export default {
  ADD_USER: 'ADD_USER',
  USERS_LIST: 'USERS_LIST',
  ADD_MESSAGE: 'ADD_MESSAGE',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  CHECK_USER_EXISTS: 'CHECK_USER_EXISTS',
  CHECK_USER_SUCCESS: 'CHECK_USER_SUCCESS',
  CONNECT_TO_CHAT_SERVER: 'CONNECT_TO_CHAT_SERVER',
};
